### PR TITLE
Fusesoc

### PR DESCRIPTION
**Pull request by cole-nelson**
Don't look through the file diffs for this, large diffs are coming from running verible format on the files and changing the spacing to 4 to be consistent with the rest of SoCET. This also cleans up many lint issues from Verilator & Verible (not all). Lint errors remaining for Verible are ones that should be waived. Verilator lint errors are things that would be good to fix in the future, but the most important lint errors (things like UNOPTFLAT) were fixed.

Things to check:
1. FuseSoC setup + build works
2. All tests pass with "run_verilator" pass as before
3. interrupt/exception tests work
4. FPGA synthesis with Quartus works (build only) using the fpga target in RISCVBusiness.core
5. Tests pass for different core configurations (i.e. I, IM, IMC)

Things that still need to be done (not as part of this PR):
1. Move modules from bus_bridges to the bus-components library
2. Waiver files for linters so lint checks will pass

### CODE REVIEW

**Comment by hadiahmed098** [comment]
I am unable to find the `fusesoc` command, is it exported somewhere public?

**Comment by hadiahmed098** [comment]
Attempting to `make verilate` creates this error about conflicting requirements.
image

**Comment by cole-nelson** [comment]
setup.sh didn't include the bus-components dependency. Please pull the update and try again.

**Review by hadiahmed098 — APPROVED** [review]

**Review by MArndt26 — APPROVED** [review]
All tests/configs worked for me

**Pull request merged**
