### PR TITLE
User Mode, v1.12 implementation

### PR DESCRIPTION
**Pull request by hadiahmed098**
This Pull Request adds the User Mode extension (U) to the CPU core. This PR also fixes some issues within the CSR unit regarding RO registers. Finally, as per the specification, the `time` and `timeh` registers are shadow copies of the memory mapped `mtime` and `mtimeh` registers, passed through the layers from the top_core module.

Things to fix:
- [x] Add 'U' to the `misa` register
- [x] Flush pipe on a mode change

### CODE REVIEW

**Review by cole-nelson — CHANGES_REQUESTED** [review]
Overall implementation looks good, just some small changes needed for clarity.

**Review by cole-nelson — APPROVED** [review]
Looks good. Tests all pass on my end after the mstatush -> mstatus fix.

**Review by MArndt26 — APPROVED** [review]
LGTM.  Tests passed but wanted to know if there are plans for integrating priv unit tests into the ./run_tests_verilator.py script to make things easier to build/run?

**Comment by hadiahmed098** [comment]
Per our discussion yesterday, I identified an issue where an exception after an interrupt in VECTORED mode would improperly vector to the wrong location. This ended up triggering a deeper look into the interrupt/exception handler, especially how it delayed interrupts by multiple cycles for no obvious reason.

Since this is a moderately major change, I am re-requesting reviews. All interrupt and exception related test cases pass on my end, but I'd like secondary confirmation.

**Review by cole-nelson — APPROVED** [review]
I think this fix makes sense. Tests all pass on my end.

**Pull request merged**
