### PR TITLE
v1.12 PMP Integration

### PR DESCRIPTION
**Pull request by hadiahmed098**
Adds the PMP v1.12 Unit to the main core. All this work is contained in the priv folder, the core integration was done with the PMA Checker.

This pull request also adds 4 test cases for the PMP. These test cases test each addressing mode and the CSRs.

TODO:
- [ ] Should the large `case` statements get condensed into a for loop?
- [x] Fix the PMA to use localparams for initialization

### CODE REVIEW

**Review by cole-nelson — CHANGES_REQUESTED** [review]
Implementation looks good. Please run the fusesoc lint target with verilator as the tool, and fix any UNOPTFLAT or other complaints generated regarding PMP/PMA. Specifically, the way that "prot_fault_*" are handled currently seems to generate a true combinational loop.

**Comment by MArndt26** [comment]
Can you provide a description of how to run the new pmp tests?

**Comment by hadiahmed098** [comment]
The new PMP tests can be run by going to the `verifications/pmp-tests` folder and running the `build_all.py` script to generate the .bin files. Run them with the Verilator generated binary.

**Comment by hadiahmed098** [comment]
I should have resolved the UNOPTFLAT issues with the most recent commit.

**Review by cole-nelson — APPROVED** [review]
Looks good, all tests pass

**Review by MArndt26 — APPROVED** [review]
All tests passed for me as well

**Pull request merged**
