### PR TITLE
Homogenous multicore implementation

### PR DESCRIPTION
**Pull request by devins2518**
# Multicore Implementation Details

### RISCV Atomic Extension Implementation
The current homogenous multicore implementation implements only the LR and SC instructions from the RISCV Atomic extension. Using these primitives, tight loops which implement larger atomic operations can be constructed. In the future, hardware atomics can be added by issuing micro-ops and making use of the `exclusive` control signal to delay a snoop response until the AMO completes.

### Configuration
The `num_harts` parameter in the config yaml file can be used to generate N harts which will all be coherent with each other. The ICache takes hart ID `N*2` and the DCache takes the hart ID `N*2+1`. In the future, this can be expanded to allow for heterogenous configurations of each core. 

### Memory Controller Updates
The memory controller is replaced with the new bus controller which performs atomic memory transactions.  The generic bus interface is expanded to allow block sized transfers of data between the bus controller and caches. The reservation set used for LR/SC implementation is block sized.

# Running Tests

## riscv-tests

riscv-tests already disables multicore execution in the startup macro, so this can just be used to ensure that new changes haven't affected single core behavior. An AMO emulation routine is provided because all tests (even LR/SC) require at least one AMO instruction to execute normally. 

- Enable A extension support in `example.yml`
- `./setup-riscv-tests.sh`
- `python3 run_riscv_tests.py --isa a`

## Cache coherency stress test

The cache coherency stress test generates a large number of transactions and simulations them on two coherent caches. The current time is used as the seed for the RNG so each run will produce different transactions. A run will generate four log files, `cache0_transactions.dump` and `cache1_transactions.dump` will show the transactions each cache ran with their time of execution, and `goldensim.dump` and `memsim.dump` will show the memory dumps of the golden model and the simulation memory respectively. 

- `cd source_code/tb/tb_cache_coherence_stress/`
- `./build.sh (<num_transactions>, optional, defaults to 1 million)`

## Multicore benchmarks

The multicore benchmarks can be found in `verification/multicore-tests/c-tests`. There are a few tests which were used to measure the performance uplift from multicore execution. In our testing, there's around 20-40% uplift which may be limited by icache size. All tests currently assume a 2 hart configuration.

- `cd verification/multicore-tests/c-tests`
- To run a test without rebuilding the core, use `./run.sh <name of test without extension>`
- To rebuild the core and run a test, use `./build_and_run.sh <name of test without extension>`

### CODE REVIEW

**Review by cole-nelson — APPROVED** [review]
LGTM. I will wait for Max to leave a review as well.

**Comment by maxmichalec** [comment]
Only concern is that it fails the RV32I `fence_i.S` self-test

**Comment by maxmichalec** [comment]
It looks like the issue is that `separate_caches` no longer has a `cache_control_if.caches` interface which controls cache flushes and clears

**Comment by devins2518** [comment]
I re-added the cache control interface, not sure how it even compiled before to be honest. I believe I remember the self-test failing before all the changes so I'm not sure if this is a regression on our side. The riscv-test version seems to have a fence_i test that passes properly if that's acceptable.

**Comment by maxmichalec** [comment]
I was running the self-tests one though I believe I found the issue: the `abort_bus` signal is not passed up through the HART to the memory controller via the multicore wrapper so when a `fence.i` follows a store to an address that is within 2 words of the `fence.i`, the D$ is snooped which returns `0xBAD1BAD1` since it is in the FLUSH_CACHE state and this is then written to memory to be loaded later on as an instruction, even though the I$ is in the CANCEL_REQ state.

The `abort_bus` signal in bus_ctrl looks to block the snoop though probably also needs to be held high until the cancelled request (read) is complete if the `requester_cpu` is the one aborting.

**Comment by devins2518** [comment]
There was some unexpected behavior due to assumptions about flushing and snooping which should be fixed now. I changed `abort_bus` to be forwarded from caches->coherency_unit->bus_ctrl which is the usual flow of data from the cache to the bus controller. I also use !wen to detect bus aborts due to some bad behavior when the dcache wanted to control the bus. Flushes are now interruptible by a snoop and continue from where they left off if interrupted.

**Comment by maxmichalec** [comment]
LGTM!

**Review by maxmichalec — APPROVED** [review]

**Pull request merged**
